from typing import TypedDict, NotRequired


class GraphState(TypedDict):
    """
    Shared state passed between LangGraph nodes.
    """

    # Task selected by the user
    task: str

    # Code generated by the LLM
    generated_code: NotRequired[str]

    review_feedback: NotRequired[str]

    # Number of review cycles completed
    iteration: NotRequired[int]

    # Whether the latest review passed
    review_passed: NotRequired[bool]

    # Future expansion:
    # context: NotRequired[str]
    # passed: NotRequired[bool]
    # model_used: NotRequired[str]