"""Push an existing local branch and open a GitHub pull request.

Skips the LLM workflow entirely — useful for testing the git/PR portion
in isolation, or for re-pushing a branch that was already prepared locally.

Usage (from the project root):

    python scripts/push_and_pr.py --branch DEV-AI-DATE-remove-type-hints-from-the-get_all-method
    python scripts/push_and_pr.py --branch my-branch --task "Short description for PR title"
    python scripts/push_and_pr.py --branch my-branch --dry-run
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config_loader import APP_CONFIG  # noqa: E402
from src.git.branch_manager import clone_if_missing, commit_file, push_branch  # noqa: E402
from src.git.pr_creator import create_pull_request  # noqa: E402


def _pick_repo():
    if not APP_CONFIG.repositories:
        raise RuntimeError("No repositories configured in config.json")
    return APP_CONFIG.repositories[0]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Push a local branch and open a GitHub PR (no LLM involved)."
    )
    parser.add_argument(
        "--branch",
        required=True,
        help="Name of the local branch to push (must already exist in the repo).",
    )
    parser.add_argument(
        "--task",
        default=None,
        help="Short description used as the PR title. Defaults to the branch name.",
    )
    parser.add_argument(
        "--commit-file",
        default=None,
        metavar="FILE",
        help="Absolute path to a file to stage and commit before pushing. "
             "Useful when testing without the full LLM workflow.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without actually pushing or creating a PR.",
    )
    args = parser.parse_args()

    repo = _pick_repo()
    branch_name: str = args.branch
    task: str = args.task or branch_name

    credentials = repo.credentials or {}
    username = credentials.get("username", "")
    token = credentials.get("token", "")

    print(f"Repository : {repo.name} ({repo.local_path})")
    print(f"Branch     : {branch_name}")
    print(f"Base branch: {repo.base_branch}")
    print(f"Remote     : {repo.url}")
    print()

    if not token:
        print("No token configured in config.json — cannot push or create PR.")
        return 1

    if args.dry_run:
        print(f"[dry-run] Would ensure repo is cloned to: {repo.local_path}")
        if args.commit_file:
            print(f"[dry-run] Would commit: {args.commit_file}")
        print("[dry-run] Would push branch to remote.")
        print(f"[dry-run] Would create PR: 'AI: {task[:72]}' → {repo.base_branch}")
        return 0

    # ── Clone if missing ─────────────────────────────────────────────────────
    print(f"Ensuring repo exists at '{repo.local_path}'…")
    try:
        clone_if_missing(
            remote_url=repo.url,
            local_path=repo.local_path,
            username=username,
            token=token,
        )
    except ValueError as exc:
        print(f"Clone failed: {exc}")
        return 1
    print()

    # ── Optional commit ───────────────────────────────────────────────────────
    if args.commit_file:
        print(f"Committing '{args.commit_file}'…")
        sha = commit_file(repo.local_path, args.commit_file, f"AI: {task}")
        if sha:
            print(f"Committed as {sha[:8]}.")
        else:
            print("Nothing to commit — file is unchanged.")
        print()

    # ── Push ─────────────────────────────────────────────────────────────────
    print(f"Pushing '{branch_name}' to origin…")
    try:
        push_branch(
            repo_path=repo.local_path,
            branch_name=branch_name,
            remote_url=repo.url,
            username=username,
            token=token,
        )
    except RuntimeError as exc:
        print(f"Push failed: {exc}")
        return 1
    print("Push complete.")
    print()

    # ── Pull request ─────────────────────────────────────────────────────────
    pr_title = f"AI: {task[:72]}"
    pr_body = (
        f"**Branch:** `{branch_name}`\n\n"
        f"**Task:** {task}\n\n"
        "Automated change generated by the locally-driven LangGraph workflow."
    )

    print("Creating pull request…")
    try:
        pr_url = create_pull_request(
            remote_url=repo.url,
            token=token,
            head_branch=branch_name,
            base_branch=repo.base_branch,
            title=pr_title,
            body=pr_body,
        )
    except RuntimeError as exc:
        print(f"PR creation failed: {exc}")
        return 1

    print(f"Pull request opened: {pr_url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
